### PR TITLE
"authenticator" and "authorizer" blueprints

### PR DESCRIPTION
**Pull request by Turbo87**
This allows the user to run e.g. `ember generate authenticator custom` to generate a `app/authenticators/custom.js` file.

### CODE REVIEW

**Comment by marcoow** [comment]
Nice! Can you add a generator for custom sessions as well? Also please use 2 spaces for indentation.

**Comment by Turbo87** [comment]
Thought I had used two spaces... I'll have another look. I haven't used
custom sessions yet so I'm not sure how they should look like.

**Comment by Turbo87** [comment]
@marcoow I've adjusted the indentation and added a "session-store" blueprint. I haven't found any documentation on using a "curstom session" so I assumed you actually meant a "custom store".

**Comment by marcoow** [comment]
Having a generator for stores is nice but can you rename that to just `"store"` and add another one for generating a [custom session](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html#L132) as well?

**Comment by Turbo87** [comment]
@marcoow I don't think using "store" is a good idea, because "store" is already used by Ember Data and we shouldn't introduce potential conflicts at that point.

**Comment by marcoow** [comment]
Yes, but isn't the generator already namespaced by the addon name?

**Comment by Turbo87** [comment]
Nope, neither the command (`ember generate session-store custom`) nor the generated file (`app/session-stores/custom.js`) are prefixed in any way. IMHO that is not a bad thing for authorizers and authenticators, but for stores we should prevent any naming conflicts.

**Comment by marcoow** [comment]
OK, makes sense

**Comment by Turbo87** [comment]
@marcoow I've added the "session" blueprint too

**Comment by marcoow** [comment]
:+1:

**Comment by Turbo87** [comment]
cool, thanks!

**Pull request merged**
